Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../cli/organisations/ordererOrganizations/orderer-org/msp
  - &MPBroker
    Name: MPBroker
    ID: MPBroker
    MSPDir: ../cli/organisations/peerOrganizations/mp-broker-org/msp
    AnchorPeers:
      - Host: mp-broker-peer
        Port: 7051
  - &CustomerA
    Name: CustomerA
    ID: CustomerA
    MSPDir: ../cli/organisations/peerOrganizations/customer-a-org/msp
    AnchorPeers:
      - Host: customer-a-peer
        Port: 7051
  - &CustomerB
    Name: CustomerB
    ID: CustomerB
    MSPDir: ../cli/organisations/peerOrganizations/customer-b-org/msp
    AnchorPeers:
      - Host: customer-b-peer
        Port: 7051
  - &CustomerC
    Name: CustomerC
    ID: CustomerC
    MSPDir: ../cli/organisations/peerOrganizations/customer-c-org/msp
    AnchorPeers:
      - Host: customer-c-peer
        Port: 7051
  - &CustomerD
    Name: CustomerD
    ID: CustomerD
    MSPDir: ../cli/organisations/peerOrganizations/customer-d-org/msp
    AnchorPeers:
      - Host: customer-d-peer
        Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:

Profiles:
  FiveOrgsGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      MarketPlaceConsortium:
        Organizations:
          - *MPBroker
          - *CustomerA
          - *CustomerB
          - *CustomerC
          - *CustomerD
  FiveOrgsChannel:
    Consortium: MarketPlaceConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *MPBroker
        - *CustomerA
        - *CustomerB
        - *CustomerC
        - *CustomerD
