Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: ../cli/organisations/ordererOrganizations/orderer-org/msp
  - &MPBrokerOrg
    Name: MPBrokerOrg
    ID: MPBrokerMSP
    MSPDir: ../cli/organisations/peerOrganizations/mp-broker-org/msp
    AnchorPeers:
      - Host: mp-broker-peer
        Port: 7051
  - &CustomerAOrg
    Name: CustomerAOrg
    ID: CustomerAMSP
    MSPDir: ../cli/organisations/peerOrganizations/customer-a-org/msp
    AnchorPeers:
      - Host: customer-a-peer
        Port: 7051
  - &CustomerBOrg
    Name: CustomerBOrg
    ID: CustomerBMSP
    MSPDir: ../cli/organisations/peerOrganizations/customer-b-org/msp
    AnchorPeers:
      - Host: customer-b-peer
        Port: 7051
  - &CustomerCOrg
    Name: CustomerCOrg
    ID: CustomerCMSP
    MSPDir: ../cli/organisations/peerOrganizations/customer-c-org/msp
    AnchorPeers:
      - Host: customer-c-peer
        Port: 7051
  - &CustomerDOrg
    Name: CustomerDOrg
    ID: CustomerDMSP
    MSPDir: ../cli/organisations/peerOrganizations/customer-d-org/msp
    AnchorPeers:
      - Host: customer-d-peer
        Port: 7051

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer0:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:

Profiles:
  FiveOrgsGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
    Consortiums:
      MarketPlaceConsortium:
        Organizations:
          - *MPBrokerOrg
          - *CustomerAOrg
          - *CustomerBOrg
          - *CustomerCOrg
          - *CustomerDOrg
  FiveOrgsChannel:
    Consortium: MarketPlaceConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *MPBrokerOrg
        - *CustomerAOrg
        - *CustomerBOrg
        - *CustomerCOrg
        - *CustomerDOrg
