OrdererOrgs:
- Name: OrdererOrg
  Domain: orderer-org
  CommonName: orderer-org
  Specs:
  - Hostname: orderer0
    CommonName: "{{.Hostname}}"
PeerOrgs:
- Name: MPBrokerOrg
  Domain: mp-broker-org
  Specs:
  - Hostname: mp-broker-peer
    CommonName: "{{.Hostname}}"
- Name: CustomerAOrg
  Domain: customer-a-org
  Specs:
  - Hostname: customer-a-peer
    CommonName: "{{.Hostname}}"
- Name: CustomerBOrg
  Domain: customer-b-org
  Specs:
  - Hostname: customer-b-peer
    CommonName: "{{.Hostname}}"
- Name: CustomerCOrg
  Domain: customer-c-org
  Specs:
  - Hostname: customer-c-peer
    CommonName: "{{.Hostname}}"
- Name: CustomerD
  Domain: customer-d-org
  Specs:
  - Hostname: customer-d-peer
    CommonName: "{{.Hostname}}"